import { useEffect, useRef, useState } from "react";
import { AnimatePresence, motion, useInView, useReducedMotion } from "framer-motion";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { ArrowDownRight, ArrowRight, CalendarDays, ChevronRight, Clock3, Instagram, Mail, MapPin, Menu, MessageCircle, Send, Sparkles, X } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { events, manifesto, monologues, navItems, pillars, rituals, rooms, stats, testimonials, type EventFormat } from "@/data/soliloqy";
import { cn } from "@/lib/utils";

const reveal = { hidden: { opacity: 0, y: 30 }, show: { opacity: 1, y: 0 } };
const fieldClass = "min-h-12 rounded-none border-2 border-midnight bg-paper px-4 text-midnight shadow-none focus-visible:ring-2 focus-visible:ring-violet";
const inkButton = "min-h-12 rounded-none border-2 border-midnight bg-pink px-6 font-bold text-paper shadow-hard transition-all hover:-translate-y-1 hover:shadow-hard-lg active:translate-y-1 active:shadow-none";

function scrollTo(id: string) {
  document.getElementById(id)?.scrollIntoView({ behavior: "smooth" });
}

export function Smiley({ className, onWink }: { className?: string; onWink?: () => void }) {
  return (
    <motion.button aria-label="Wink and throw confetti" type="button" onClick={onWink} whileTap={{ scale: 0.82 }} className={cn("smiley-button", className)}>
      <svg viewBox="0 0 120 120" role="img" aria-label="Winking SOLILOQY smiley">
        <circle cx="60" cy="60" r="54" fill="var(--yellow)" stroke="var(--midnight)" strokeWidth="6" />
        <path d="M27 43q13-12 25 0" fill="none" stroke="var(--midnight)" strokeWidth="7" strokeLinecap="round" />
        <ellipse cx="82" cy="44" rx="6" ry="10" fill="var(--midnight)" className="smiley-eye" />
        <path d="M30 66q28 36 59 1" fill="none" stroke="var(--midnight)" strokeWidth="7" strokeLinecap="round" />
        <path d="M66 82q13 14 23-5q-12-3-23 5Z" fill="var(--pink)" stroke="var(--midnight)" strokeWidth="4" />
      </svg>
    </motion.button>
  );
}

function Confetti({ burst }: { burst: number }) {
  if (!burst) return null;
  return <div key={burst} className="pointer-events-none fixed inset-0 z-[100] overflow-hidden" aria-hidden>{Array.from({ length: 26 }, (_, i) => <i key={i} className={cn("confetti", i % 3 === 0 ? "bg-yellow" : i % 3 === 1 ? "bg-pink" : "bg-violet")} style={{ left: `${10 + ((i * 37) % 80)}%`, animationDelay: `${(i % 8) * 40}ms`, transform: `rotate(${i * 29}deg)` }} />)}</div>;
}

function Navbar() {
  const [open, setOpen] = useState(false);
  const [active, setActive] = useState("home");
  useEffect(() => {
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActive(entry.target.id)), { rootMargin: "-35% 0px -55%" });
    navItems.forEach(([, id]) => { const el = document.getElementById(id); if (el) observer.observe(el); });
    return () => observer.disconnect();
  }, []);
  const go = (id: string) => { scrollTo(id); setOpen(false); };
  return (
    <header className="fixed inset-x-0 top-0 z-50 border-b-2 border-midnight/15 bg-paper/90 backdrop-blur-xl">
      <nav className="mx-auto flex h-18 max-w-[1440px] items-center justify-between px-5 lg:px-10" aria-label="Main navigation">
        <button type="button" onClick={() => go("home")} className="flex items-center gap-2" aria-label="SOLILOQY home"><span className="font-display text-2xl font-extrabold">SOLILOQY</span><span className="text-xl">😜</span></button>
        <div className="hidden items-center gap-7 lg:flex">{navItems.map(([label, id]) => <button key={id} type="button" onClick={() => go(id)} className={cn("relative py-2 text-sm font-bold transition-colors after:absolute after:inset-x-0 after:bottom-0 after:h-1 after:origin-left after:bg-pink after:transition-transform", active === id ? "after:scale-x-100" : "after:scale-x-0 hover:after:scale-x-100")}>{label}</button>)}</div>
        <Button onClick={() => go("contact")} className={cn(inkButton, "hidden lg:inline-flex")}>Join the Monologue <ArrowRight /></Button>
        <Button variant="ghost" size="icon" onClick={() => setOpen((v) => !v)} className="lg:hidden" aria-label={open ? "Close menu" : "Open menu"}>{open ? <X /> : <Menu />}</Button>
      </nav>
      <AnimatePresence>{open && <motion.div initial={{ x: "100%" }} animate={{ x: 0 }} exit={{ x: "100%" }} className="absolute right-0 top-full min-h-[calc(100vh-4.5rem)] w-full border-l-2 border-midnight bg-yellow p-7 sm:w-96"><div className="flex flex-col gap-3">{navItems.map(([label, id], i) => <button key={id} onClick={() => go(id)} type="button" className="flex items-center justify-between border-b-2 border-midnight py-4 text-left font-display text-3xl font-extrabold"><span>0{i + 1}. {label}</span><ChevronRight /></button>)}</div></motion.div>}</AnimatePresence>
    </header>
  );
}

function Cube3D() {
  const [tilt, setTilt] = useState({ x: -14, y: 24 });
  return <div className="cube-scene" onPointerMove={(e) => { const r = e.currentTarget.getBoundingClientRect(); setTilt({ x: ((e.clientY - r.top) / r.height - .5) * -30, y: ((e.clientX - r.left) / r.width - .5) * 35 }); }} onPointerLeave={() => setTilt({ x: -14, y: 24 })} aria-hidden><div className="cube" style={{ transform: `rotateX(${tilt.x}deg) rotateY(${tilt.y}deg)` }}><div className="cube-face cube-front dot-grid"/><div className="cube-face cube-back"/><div className="cube-face cube-right wave-grid"/><div className="cube-face cube-left"/><div className="cube-face cube-top"/><div className="cube-face cube-bottom dot-grid"/></div></div>;
}

function Typewriter() {
  const [line, setLine] = useState(0); const [text, setText] = useState(""); const reduce = useReducedMotion();
  useEffect(() => { if (reduce) { setText(monologues[0]); return; } const full = monologues[line]; let i = 0; const typing = window.setInterval(() => { i += 1; setText(full.slice(0, i)); if (i === full.length) { clearInterval(typing); window.setTimeout(() => { setText(""); setLine((v) => (v + 1) % monologues.length); }, 1400); } }, 55); return () => clearInterval(typing); }, [line, reduce]);
  return <p className="min-h-9 font-hand text-2xl font-bold">“{text}<span className="animate-pulse">|</span>”</p>;
}

function Hero({ wink }: { wink: () => void }) {
  const words = "Speak your mind. We're listening.".split(" ");
  return <section id="home" className="relative min-h-[860px] overflow-hidden bg-yellow pt-28 lg:min-h-[760px]"><div className="dot-grid absolute right-0 top-24 h-52 w-52 opacity-30"/><div className="absolute -left-16 top-56 h-40 w-40 rounded-full border-[28px] border-pink"/><div className="relative mx-auto grid max-w-[1440px] gap-10 px-5 pb-20 pt-10 lg:grid-cols-[1.1fr_.9fr] lg:px-10 lg:pt-20"><div className="z-10"><div className="mb-6 inline-flex -rotate-2 border-2 border-midnight bg-paper px-4 py-2 font-hand text-xl font-bold shadow-hard-sm">The Open Monologue ✦</div><h1 className="max-w-4xl font-display text-[clamp(4rem,10vw,9.5rem)] font-extrabold leading-[.82]">{words.map((word, i) => <motion.span key={word+i} initial={{ opacity: 0, y: 50, rotate: i === 2 ? 4 : 0 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .08 * i, type: "spring", stiffness: 150 }} className={cn("mr-[.18em] inline-block", word === "mind." && "text-pink")}>{word}</motion.span>)}</h1><p className="mt-8 max-w-xl text-lg font-medium sm:text-xl">A safe haven for solo thinkers, quirky creators and honest internal dialogue.</p><div className="mt-6"><Typewriter /></div><div className="mt-8 flex flex-wrap gap-4"><Button onClick={() => scrollTo("contact")} className={inkButton}>Join the Community <ArrowRight /></Button><Button onClick={() => scrollTo("events")} variant="outline" className="min-h-12 rounded-none border-2 border-midnight bg-transparent px-6 font-bold shadow-hard-sm hover:bg-paper">See Events <CalendarDays /></Button></div><p className="mt-7 -rotate-2 font-hand text-xl">psst… drafts welcome ↗</p></div><div className="relative flex min-h-80 items-center justify-center"><Cube3D/><Smiley onWink={wink} className="absolute bottom-0 right-[5%] w-28 rotate-12 lg:w-36"/><div className="absolute left-[8%] top-[8%] h-16 w-36 rotate-12 rounded-full bg-violet"/><div className="absolute right-[7%] top-[8%] h-20 w-20 rounded-tl-full bg-pink"/></div></div><div className="absolute bottom-0 left-0 h-6 w-full torn-top bg-paper"/></section>;
}

function SectionTitle({ eyebrow, children, light = false }: { eyebrow: string; children: React.ReactNode; light?: boolean }) {
  return <div className="mb-12"><p className={cn("mb-3 font-mono text-xs font-bold uppercase tracking-[.2em]", light ? "text-yellow" : "text-pink")}>{eyebrow}</p><h2 className={cn("max-w-5xl font-display text-5xl font-extrabold leading-[.9] sm:text-7xl lg:text-8xl", light && "text-paper")}>{children}</h2><svg className="mt-4 h-4 w-64" viewBox="0 0 260 15" aria-hidden><motion.path d="M3 8c38-9 74 8 113 0s76 7 140-2" fill="none" stroke="currentColor" strokeWidth="5" strokeLinecap="round" initial={{ pathLength: 0 }} whileInView={{ pathLength: 1 }} viewport={{ once: true }} transition={{ duration: .8 }} /></svg></div>;
}

function Reveal({ children, className }: { children: React.ReactNode; className?: string }) { return <motion.div variants={reveal} initial="hidden" whileInView="show" viewport={{ once: true, amount: .15 }} transition={{ duration: .55 }} className={className}>{children}</motion.div>; }

function CountUp({ value, suffix }: { value: number; suffix: string }) {
  const ref = useRef<HTMLSpanElement>(null); const seen = useInView(ref, { once: true }); const [display, setDisplay] = useState(0);
  useEffect(() => { if (!seen || value === 0) return; const start = performance.now(); const frame = (now: number) => { const p = Math.min((now - start) / 1100, 1); setDisplay(Math.round(value * (1 - Math.pow(1 - p, 3)))); if (p < 1) requestAnimationFrame(frame); }; requestAnimationFrame(frame); }, [seen, value]);
  return <span ref={ref}>{value === 0 ? suffix : `${display.toLocaleString()}${suffix}`}</span>;
}

function About() { return <section id="about" className="bg-paper py-24 lg:py-32"><div className="mx-auto max-w-[1440px] px-5 lg:px-10"><SectionTitle eyebrow="01 / Why we're here">What's a soliloquy anyway?</SectionTitle><div className="grid gap-8 lg:grid-cols-2"><Reveal><div className="border-3 border-midnight bg-yellow p-7 shadow-hard-lg sm:p-10"><p className="font-display text-3xl font-extrabold sm:text-5xl">soliloquy <em className="font-hand text-pink">(n.)</em></p><p className="mt-5 text-xl leading-relaxed">the act of speaking your thoughts aloud when by yourself.</p><p className="mt-8 border-t-2 border-midnight pt-5 font-hand text-2xl">See also: being delightfully human.</p></div></Reveal><Reveal><div className="flex h-full flex-col justify-between gap-8"><p className="text-xl leading-relaxed sm:text-2xl">While the digital world demands performative polish, SOLILOQY is built for what happens <strong>before the performance:</strong> half-formed thoughts in midnight notebooks, honest internal debates that spark breakthroughs, and the playful, vulnerable dialogue that makes us human.</p><blockquote className="border-l-8 border-pink pl-6 font-display text-3xl font-extrabold leading-tight sm:text-5xl">“From Inner Voice to Outer Resonance.”</blockquote></div></Reveal></div><div className="mt-16 grid grid-cols-2 border-3 border-midnight bg-midnight text-paper md:grid-cols-4">{stats.map((stat) => <div key={stat.label} className="border-paper/25 p-5 even:border-l md:border-l md:first:border-l-0 sm:p-7"><strong className="font-display text-4xl text-yellow sm:text-6xl"><CountUp value={stat.value} suffix={stat.suffix}/></strong><span className="mt-1 block text-sm font-bold uppercase">{stat.label}</span></div>)}</div></div></section>; }

function PillarCard({ pillar, index }: { pillar: typeof pillars[number]; index: number }) { const tone = { yellow: "bg-yellow text-midnight", pink: "bg-pink text-paper", purple: "bg-violet text-paper" }[pillar.tone]; return <motion.article whileHover={{ y: -10, rotate: index === 1 ? 1.5 : -1.5 }} className={cn("group min-h-96 border-3 border-paper p-7 shadow-hard-paper transition-shadow hover:shadow-hard-paper-lg", tone)}><div className="flex justify-between"><span className="font-mono text-sm font-bold">{pillar.number}</span><ArrowDownRight className="h-10 w-10 transition-transform group-hover:rotate-45"/></div><div className="mt-24"><h3 className="font-display text-4xl font-extrabold leading-none">{pillar.title}</h3><p className="mt-5 font-hand text-3xl font-bold">{pillar.kicker}</p><p className="mt-4 text-lg leading-relaxed">{pillar.body}</p></div></motion.article>; }

function WhatWeDo() { return <section id="what-we-do" className="bg-midnight py-24 lg:py-32"><div className="mx-auto max-w-[1440px] px-5 lg:px-10"><SectionTitle eyebrow="02 / The good stuff" light>Messy minds. <span className="text-pink">Shared.</span></SectionTitle><div className="grid gap-6 lg:grid-cols-3">{pillars.map((p, i) => <Reveal key={p.title}><PillarCard pillar={p} index={i}/></Reveal>)}</div><Reveal className="mt-20"><div className="flex items-end justify-between gap-4"><div><p className="font-hand text-2xl text-yellow">A week in the life →</p><h3 className="font-display text-4xl font-extrabold text-paper sm:text-6xl">Weekly Rituals</h3></div></div><div className="mt-8 grid border-t-2 border-paper/30 lg:grid-cols-4">{rituals.map((r) => <article key={r.title} className="border-b-2 border-paper/30 py-7 lg:border-b-0 lg:border-r lg:px-6 lg:first:pl-0 lg:last:border-r-0"><div className="mb-6 flex items-center justify-between"><span className="text-3xl">{r.icon}</span><span className="rounded-full border border-paper/40 px-3 py-1 font-mono text-xs text-paper">{r.day}</span></div><h4 className="font-display text-2xl font-extrabold text-yellow">{r.title}</h4><p className="mt-3 leading-relaxed text-paper/75">{r.body}</p></article>)}</div></Reveal></div></section>; }

function Marquee() { const text = "RAW BEATS POLISHED ✦ TOGETHER, ALONE ✦ DEEP DOESN'T MEAN DREARY ✦ SPEAK YOUR MIND 😜 ✦ "; return <div className="marquee -rotate-1 border-y-3 border-midnight bg-yellow py-4" aria-label={text}><div className="marquee-track font-display text-2xl font-extrabold">{text.repeat(4)}</div></div>; }

const rsvpSchema = z.object({ name: z.string().min(2, "Tell us what to call you."), email: z.string().email("Try a real email address.") });
type RsvpFields = z.infer<typeof rsvpSchema>;
function RSVP({ title }: { title: string }) { const [open, setOpen] = useState(false); const { register, handleSubmit, formState: { errors }, reset } = useForm<RsvpFields>({ resolver: zodResolver(rsvpSchema) }); const submit = () => { toast.success("You're on the list. Bring your inside voice 😜"); reset(); setOpen(false); }; return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button className="rounded-none border-2 border-midnight bg-paper font-bold text-midnight shadow-hard-sm hover:bg-yellow">RSVP <ArrowRight/></Button></DialogTrigger><DialogContent className="max-w-md rounded-none border-3 border-midnight bg-yellow shadow-hard-lg"><DialogHeader><DialogTitle className="font-display text-4xl font-extrabold">Save your spot.</DialogTitle><DialogDescription className="text-base text-midnight/70">{title}. No polished introduction required.</DialogDescription></DialogHeader><form onSubmit={handleSubmit(submit)} className="mt-4 space-y-4"><label className="block font-bold">Name<Input {...register("name")} className={cn(fieldClass, "mt-1")}/>{errors.name && <span className="mt-1 block text-sm text-destructive">{errors.name.message}</span>}</label><label className="block font-bold">Email<Input type="email" {...register("email")} className={cn(fieldClass, "mt-1")}/>{errors.email && <span className="mt-1 block text-sm text-destructive">{errors.email.message}</span>}</label><Button type="submit" className={cn(inkButton, "w-full")}>I'm in <Sparkles/></Button></form></DialogContent></Dialog>; }

function Events() { const [filter, setFilter] = useState<"All" | EventFormat>("All"); const shown = events.filter((e) => filter === "All" || e.format === filter); return <section id="events" className="bg-pink py-24 text-paper lg:py-32"><div className="mx-auto max-w-[1440px] px-5 lg:px-10"><SectionTitle eyebrow="03 / Pull up a thought" light>Come think out loud <span className="text-yellow">(quietly).</span></SectionTitle><div className="mb-10 flex flex-wrap gap-3" aria-label="Filter events">{(["All", "Online", "In-person", "Async"] as const).map((f) => <Button key={f} type="button" onClick={() => setFilter(f)} aria-pressed={filter === f} className={cn("rounded-full border-2 border-midnight px-5 font-bold text-midnight shadow-none", filter === f ? "bg-yellow" : "bg-paper hover:bg-yellow")}>{f}</Button>)}</div><motion.div layout className="grid gap-5 md:grid-cols-2 lg:grid-cols-3"><AnimatePresence mode="popLayout">{shown.map((event, i) => <motion.article layout initial={{ opacity: 0, scale: .9 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0, scale: .9 }} whileHover={{ y: -8, rotate: i % 2 ? 1 : -1 }} key={event.title} className="flex min-h-80 flex-col border-3 border-midnight bg-paper p-6 text-midnight shadow-hard-lg"><div className="flex items-start justify-between"><div className="border-2 border-midnight bg-yellow px-3 py-2 text-center shadow-hard-sm"><strong className="block font-display text-3xl leading-none">{event.date}</strong><span className="font-mono text-xs font-bold">{event.month}</span></div><span className="rounded-full bg-midnight px-3 py-1 text-xs font-bold text-paper">{event.format}</span></div><h3 className="mt-8 font-display text-3xl font-extrabold leading-none">{event.title}</h3><p className="mt-3 flex items-center gap-2 text-sm font-bold"><Clock3 className="h-4 w-4"/>{event.time}</p><div className="mt-auto pt-6"><RSVP title={event.title}/></div></motion.article>)}</AnimatePresence></motion.div></div></section>; }

function Spaces() { return <section id="spaces" className="bg-paper py-24 lg:py-32"><div className="mx-auto max-w-[1440px] px-5 lg:px-10"><SectionTitle eyebrow="04 / Choose your corner">Pick a room.</SectionTitle><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-5">{rooms.map((room, i) => <motion.article whileHover="open" initial="closed" key={room.name} className={cn("group relative min-h-80 overflow-hidden border-3 border-midnight p-5 shadow-hard", i % 2 ? "bg-yellow" : "bg-pink text-paper")}><div className="absolute inset-x-7 bottom-0 top-16 border-3 border-midnight bg-midnight p-4 text-paper"><span className="font-hand text-xl">{room.aside}</span><div className="absolute bottom-5 right-4 h-3 w-3 rounded-full bg-yellow"/></div><motion.div variants={{ closed: { rotateY: 0 }, open: { rotateY: -74 } }} transition={{ type: "spring", stiffness: 120 }} style={{ transformOrigin: "left", transformStyle: "preserve-3d" }} className="absolute inset-x-7 bottom-0 top-16 border-3 border-midnight bg-paper p-5 text-midnight"><div className="absolute right-4 top-1/2 h-3 w-3 rounded-full bg-pink"/></motion.div><div className="relative z-10"><span className="font-mono text-xs font-bold">ROOM 0{i + 1}</span><h3 className="mt-3 break-words font-display text-2xl font-extrabold">{room.name}</h3><p className="mt-2 text-sm font-medium">{room.body}</p></div></motion.article>)}</div></div></section>; }

function Manifesto() { return <section className="relative overflow-hidden bg-violet py-24 text-paper lg:py-36"><div className="absolute inset-0 wave-grid opacity-10"/><div className="relative mx-auto max-w-6xl px-5 text-center"><p className="mb-10 font-mono text-xs font-bold uppercase tracking-[.25em] text-yellow">The Open Monologue Manifesto</p>{manifesto.map((line, i) => <motion.p key={line} initial={{ opacity: .12 }} whileInView={{ opacity: 1 }} viewport={{ amount: .75 }} transition={{ duration: .6 }} className={cn("font-display font-extrabold leading-[1.02]", i === manifesto.length - 1 ? "mt-10 text-5xl text-yellow sm:text-7xl" : "mb-6 text-3xl sm:text-5xl")}>{line}</motion.p>)}</div></section>; }

function Testimonials() { return <section className="bg-paper py-24"><div className="mx-auto max-w-[1440px] px-5 lg:px-10"><p className="mb-9 font-hand text-3xl font-bold">Notes passed under the table ↓</p><div className="grid gap-8 md:grid-cols-3">{testimonials.map((t, i) => <motion.blockquote whileHover={{ rotate: 0, y: -6 }} key={t.name} className={cn("border-3 border-midnight p-7 shadow-hard", i === 1 ? "rotate-2 bg-pink text-paper" : i === 2 ? "-rotate-1 bg-yellow" : "-rotate-2 bg-violet text-paper")}><MessageCircle className="h-8 w-8"/><p className="mt-6 font-display text-2xl font-bold leading-tight">“{t.quote}”</p><footer className="mt-7 font-hand text-xl">— {t.name}</footer></motion.blockquote>)}</div></div></section>; }

const joinSchema = z.object({ name: z.string().min(2, "Give us at least two letters."), email: z.string().email("That email looks a little too abstract."), thought: z.string().min(10, "Let the thought wander for at least 10 characters."), interest: z.string().min(1, "Pick the room that feels most you.") });
type JoinFields = z.infer<typeof joinSchema>;
function ContactForm() { const { register, handleSubmit, reset, formState: { errors } } = useForm<JoinFields>({ resolver: zodResolver(joinSchema) }); const submit = () => { toast.success("Got it. Your monologue is in. 😜"); reset(); }; return <form onSubmit={handleSubmit(submit)} noValidate className="space-y-5"><div className="grid gap-5 sm:grid-cols-2"><label className="font-bold">Your name<Input {...register("name")} className={cn(fieldClass, "mt-2")} placeholder="The real one or a fun one"/>{errors.name && <span className="mt-1 block text-sm text-destructive">{errors.name.message}</span>}</label><label className="font-bold">Email address<Input {...register("email")} type="email" className={cn(fieldClass, "mt-2")} placeholder="you@somewhere.com"/>{errors.email && <span className="mt-1 block text-sm text-destructive">{errors.email.message}</span>}</label></div><label className="block font-bold">What's the conversation in your head today?<Textarea {...register("thought")} className={cn(fieldClass, "mt-2 min-h-36 py-3")} placeholder="Start in the middle. We’ll catch up."/>{errors.thought && <span className="mt-1 block text-sm text-destructive">{errors.thought.message}</span>}</label><label className="block font-bold">I'm most interested in…<select {...register("interest")} defaultValue="" className={cn(fieldClass, "mt-2 w-full appearance-none")}><option value="" disabled>Choose your kind of quiet</option><option>Silent co-working</option><option>Sharing unfinished work</option><option>Creative conversations</option><option>All of the above, obviously</option></select>{errors.interest && <span className="mt-1 block text-sm text-destructive">{errors.interest.message}</span>}</label><Button type="submit" className={cn(inkButton, "w-full sm:w-auto")}>Send my monologue <Send/></Button></form>; }

function Contact() { return <section id="contact" className="bg-yellow py-24 lg:py-32"><div className="mx-auto max-w-[1440px] px-5 lg:px-10"><SectionTitle eyebrow="05 / Your turn">Say it out loud.</SectionTitle><div className="grid gap-10 lg:grid-cols-[1.3fr_.7fr]"><Reveal><ContactForm/></Reveal><Reveal><aside className="border-3 border-midnight bg-midnight p-7 text-paper shadow-hard-pink"><Smiley className="mb-7 w-24"/><h3 className="font-display text-3xl font-extrabold">Prefer a side note?</h3><a href="mailto:hello@soliloqy.community" className="mt-5 flex items-center gap-3 font-bold text-yellow hover:underline"><Mail/>hello@soliloqy.community</a><div className="mt-8 flex gap-3"><Button size="icon" aria-label="Instagram" className="rounded-full border-2 border-paper bg-pink"><Instagram/></Button><Button size="icon" aria-label="Community chat" className="rounded-full border-2 border-paper bg-violet"><MessageCircle/></Button></div><p className="mt-10 -rotate-2 border-t border-paper/30 pt-6 font-hand text-2xl">Your weird little thought might be somebody else's missing piece. ↗</p></aside></Reveal></div></div></section>; }

function Footer() { return <footer className="bg-midnight px-5 pb-8 pt-20 text-paper lg:px-10"><div className="mx-auto max-w-[1440px]"><div className="flex flex-col justify-between gap-8 border-b border-paper/25 pb-14 lg:flex-row lg:items-end"><h2 className="font-display text-[clamp(4.5rem,15vw,13rem)] font-extrabold leading-[.7] text-yellow">SOLILOQY</h2><Smiley className="w-24"/></div><div className="flex flex-col justify-between gap-6 pt-8 text-sm md:flex-row"><p>Made for solo thinkers, together. © 2026 Soliloqy.</p><div className="flex flex-wrap gap-5">{navItems.map(([label, id]) => <button key={id} type="button" onClick={() => scrollTo(id)} className="font-bold hover:text-yellow">{label}</button>)}</div></div></div></footer>; }

function CursorFollower() { const [p, setP] = useState({ x: -30, y: -30 }); useEffect(() => { const move = (e: MouseEvent) => setP({ x: e.clientX, y: e.clientY }); window.addEventListener("mousemove", move); return () => window.removeEventListener("mousemove", move); }, []); return <motion.div animate={{ x: p.x - 10, y: p.y - 10 }} transition={{ type: "spring", stiffness: 500, damping: 35 }} className="pointer-events-none fixed left-0 top-0 z-[90] hidden h-5 w-5 rounded-full bg-yellow mix-blend-difference lg:block" aria-hidden/>; }

export function SoliloqySite() { const [burst, setBurst] = useState(0); return <><CursorFollower/><Confetti burst={burst}/><Navbar/><main><Hero wink={() => setBurst(Date.now())}/><About/><WhatWeDo/><Marquee/><Events/><Spaces/><Manifesto/><Testimonials/><Contact/></main><Footer/><Smiley onWink={() => setBurst(Date.now())} className="fixed bottom-5 right-5 z-40 w-16 -rotate-6 shadow-hard-sm"/></>; }